title: 'Atelier IA'
email: alexia.schneider@umontreal.ca
description: Support des ateliers IA pour les SHS organisés par le laboratoire sur les Écritures numériques de l'Université de Montréal

theme: minima
---
